config/routes.rb
SelfErp::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    root :to => "welcome#index"
    get 'login', :to => 'devise/sessions#new', :as => :login
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "welcome/index"
  get "component_category_select/children_collection"
  get "component_category_select/cc_code"

  root :to => 'devise/sessions#new'

end

app/models/component_category.rb
class ComponentCategory < ActiveRecord::Base
  before_destroy :check_and_delete_children
  has_ancestry(:cache_depth => true)
  # attr_accessible :title, :body
  attr_accessible :name, :code, :updated_by_email, :parent, :ancestry,:ancestry_depth,
                  :level0, :level1, :level2, :comment, :part_numbers_attributes, :parent_id

  has_many :part_numbers, :dependent => :destroy, :inverse_of => :component_category
  accepts_nested_attributes_for :part_numbers, :allow_destroy => true  

  validates_presence_of :name
  validates_presence_of :code
  validates_uniqueness_of :name, :scope => [:ancestry]
  validates_uniqueness_of :code, :scope => [:ancestry]	
  validates_format_of :code, :with => /\A([0][1-9]|[1-9][0-9])$\z/
  validates :updated_by_email, :presence => { :case_sensitive => false }	
  validates_format_of :updated_by_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i  

  scope :depth0, where(:ancestry_depth => 0)
  scope :depth1, where(:ancestry_depth => 1)
  scope :depth2, where(:ancestry_depth => 2)
  scope :depth3, where(:ancestry_depth => 3) 
  scope :valid_depth0_collection, Proc.new{depth0.select{|c| c.descendants.exists?(:ancestry_depth => 3)}}

  attr_accessor :level0, :level1, :level2

  def level0
    self.root_id
  end

  def level1
    self.ancestor_ids[1]
  end

  def level2
    self.ancestor_ids[2]
  end

  def end_node?
	  #self.ancestry_depth==3?  true:false
    self.children.empty?
  end  

  def full_display
    unless self.ancestors.nil? 
      @full_name = self.path.to_ary.map{|c| "#{c.name}(#{c.code})"}
      @full_name.join("-")
    end    
  end

  def ancestor_display
    unless self.ancestors.nil? 
      @parents_name = self.ancestors.to_ary.map{|c| "#{c.name}(#{c.code})"}
      @parents_name.join("-")
    end
  end

  def code_generator
    unless (self.ancestors.nil? || self.ancestry_depth != 3) 
      @code = self.path.to_ary.map{|c| "#{c.code}"}
      @code.join
    end
  end

  def partial_code
    self.path.to_ary.map{|c| "#{c.code}"}.join
  end

  #def associated_parts (id, group_id)
    #self.part_numbers.reject{|pn| pn.group_id.blank? || pn.group_id != group_id || pn.id == id}
    #self.part_numbers.select{|pn| pn.group_id? && pn.group_id == group_id && pn.id != id}
  #end

  def group_id_options
    # In reality, each group shall include at least 2 components so that the maximum
    # group number is half of size. 
    #@size = self.part_numbers.size
    #[""] + Array.new(@size.even?? @size.div(2):@size.div(2)+1) {|i| i+1}
    [""] + Array.new(self.part_numbers.size.div(2)) {|i| i+1}
  end

  def preference_options
    [""] + Array.new(self.part_numbers.size) {|i| i+1}
  end

  def check_and_delete_children
    # the below checking is for test purpose
    #if self.ancestry_depth == 3 
    #  self.errors.add(:base, :destroy_fails_if_in_use, :categoryname => self.name)
    #  return false
    #end   
    self.children.each do |c|
      unless c.destroy
      self.errors[:base].concat(c.errors[:base]);
      self.errors.add(:base, :destroy_fails_if_children_exist, :childname => c.name) 
      return false
      end
    end
  end

  def end_leaves
    self.subtree.select{|node| node.end_node?}
  end

  scope :level0_eq, lambda {|id| ComponentCategory.find(id).subtree unless id.nil?} 
  scope :level1_eq, lambda {|id| ComponentCategory.find(id).subtree unless id.nil?} 
  scope :level2_eq, lambda {|id| ComponentCategory.find(id).subtree unless id.nil?}
  search_methods :level0_eq, :level1_eq, :level2_eq

end

app/views/admin/component_categories/_new_form.html.erb
<%= semantic_form_for [:admin, @component_category] do |f| %>
  <%= f.inputs :component_category_sel_category_type do %>
    <%= f.input :ancestry_depth, :as => :select, :input_html => {:class => "new_form_component_category_ancestry_depth"},
                :include_blank => true,
                :collection => 
                COMPONENT_CATEGORY_MAP.each_with_index.map { |x,i| [I18n.t("label.component_category.#{x}"),i]} %>    
    <%= render :partial => "sel_ancestor_new_form", 
               :locals => {:f => f, :top_collection => ComponentCategory.depth0,
                           :form_class => "cc_selection"} %>     
  <% end %>    

  <%= f.inputs :name => "hidden area", :style => "display:none;" do %>
    <%= f.input :parent_id %> 
    <%= f.input :updated_by_email, 
                :input_html => {:value => f.object.updated_by_email || current_admin_user.email} %>
  <% end %>

  <%= f.inputs :component_category_list_category_details do  %>    
    <%= f.input :name %>
    <%= f.input :code, :as => :string%>    
    <%= f.input :comment %>
  <% end %>
  
  <%= f.actions do %>
    <%= f.action :submit %>
    <li class="cancel"> 
      <%=link_to I18n.t("active_admin.cancel"), component_category_collection_url_help(f.object.ancestry_depth)%>
    </li>
  <% end %>
<% end %>      

app/views/admin/component_categories/_search.html.erb
<%= form_for @search, :url => collection_path, :as => :q, :builder => ActiveAdmin::Filters::FormBuilder, :html => {method: :get, :class => "component_category_filter_form filter_form"} do |f| %>

  <%=         
    f.filter :level0, :as => :select, :collection => Proc.new{ComponentCategory.depth0}, 
             :input_html => {:class => "search_cc_selection"} 
    f.filter :level1, :as => :select, :input_html => {:class => "search_cc_selection"},
             :collection => f.object.level0_eq.blank?? [] 
                          : Proc.new{ComponentCategory.find(f.object.level0_eq).children}
    f.filter :level2, :as => :select, :input_html => {:class => "search_cc_selection"},
             :collection => f.object.level1_eq.blank?? [] 
                          : Proc.new{ComponentCategory.find(f.object.level1_eq).children}

    f.filter :name, :as => :string
    f.filter :updated_by_email, :as => :select, 
             :collection => proc {ComponentCategory.uniq.pluck(:updated_by_email)}
    f.form_buffers.last %>

  <%= content_tag :div, :class => "buttons" do %>
    <%=  f.submit I18n.t('active_admin.filter') %>
    <%=  link_to(I18n.t('active_admin.clear_filters'), "#", :class => "clear_filters_btn") %>
    <%=  hidden_field_tags_for(params, :except => [:q, :page]) %>
  <% end %>

<% end %> 

app/views/admin/component_categories/_sel_ancestor_new_form.html.erb
<%= f.input :level0, :as => :select, :input_html => {:class => form_class},
            :collection => top_collection, 
            :prompt => I18n.t('helpers.select.category_sel_tip_prompt') %>
<%= f.input :level1, :as => :select, :input_html => {:class => form_class},
            :collection => f.object.level0.blank?? [] 
                         : ComponentCategory.find(f.object.level0).children,
            :prompt => I18n.t('helpers.select.category_sel_tip_prompt') %>
<%= f.input :level2, :as => :select, :input_html => {:class => form_class},
            :collection => f.object.level1.blank?? [] 
                         : ComponentCategory.find(f.object.level1).children,
            :prompt => I18n.t('helpers.select.category_sel_tip_prompt') %> 

app/views/admin/component_categories/edit_group.html.erb
<%= semantic_form_for [:admin, @component_category], :url => set_group_admin_component_category_path do |f| %>
  <table border="0" cellspacing="0" cellpadding="0" class="index_table">
    <thead>
      <tr>
        <th><%= i18n_helper("part_number","code") %></th>
        <th><%= i18n_helper("part_number","component_category_id") %></th>
        <th><%= i18n_helper("part_number","supplier") %></th>
        <th><%= i18n_helper("part_number","description") %></th>
        <th><%= i18n_helper("part_number","status") %></th>  
        <th><%= i18n_helper("part_number","group_id") %></th>
        <th><%= i18n_helper("part_number","preference") %></th>        
      </tr>
    </thread>            
    <tbody>
      <%= f.fields_for :part_numbers do |part_number|%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= link_to "#{part_number.object.code}", admin_part_number_url(part_number.object.id) %></td>
          <td><%= part_number.object.associated_component_category %></td>
          <td><%= part_number.object.associated_supplier %></td>
          <td><%= part_number.object.description %></td>
          <td><%= i18n_status_helper(part_number.object.status) %></td>
          <td><%= part_number.select :group_id, @component_category.group_id_options %></td>
          <td><%= part_number.select :preference, @component_category.preference_options %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= f.actions do %>
    <%= f.action :submit %>
    <li class="cancel"> 
      <%=link_to I18n.t("active_admin.cancel"), admin_part_numbers_url%>
    </li>
  <% end %>
<% end %>