config/routes.rb
SelfErp::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    root :to => "welcome#index"
    get 'login', :to => 'devise/sessions#new', :as => :login
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "welcome/index"
  get "component_category_select/children_collection"
  get "component_category_select/cc_code"

  root :to => 'devise/sessions#new'

end

app/views/admin/share/_action_links.erb
  <%= f.actions do %>
    <%= f.action :submit %>
    <li class="cancel"> <%=link_to t("active_admin.cancel"), {:action => :index} %></li>
  <% end %>

app/views/admin/share/_appendix.erb
<li class="appendix input optional">
  <%= f.label :appendix %>
  <% if f.object.appendix? %>
    <%= f.object.appendix_name %> &nbsp&nbsp
    <%= f.check_box :remove_appendix %> Remove &nbsp&nbsp
  <% end %>
  <%= f.file_field :appendix %>
</li>

app/views/admin/share/_bom_appendix.erb
<li>
  <%= f.label :bom_appendix %>
  <% if f.object.bom_appendix? %>
    <%= f.object.bom_appendix_name %> &nbsp&nbsp
    <%= f.check_box :remove_bom_appendix %> Remove &nbsp&nbsp
  <% end %>
  <%= f.file_field :bom_appendix %>
</li>

app/views/admin/share/_search_action_links.erb
  <%= content_tag :div, :class => "buttons" do %>
    <%=  f.submit I18n.t('active_admin.filter') %>
    <%=  link_to(I18n.t('active_admin.clear_filters'), "#", :class => "clear_filters_btn") %>
    <%=  hidden_field_tags_for(params, :except => [:q, :page]) %>
  <% end %> 

app/views/admin/share/_status_field.erb
<%= f.inputs :status_info do %>
  <%= f.input :status, :as => :select, :collection => f.object.status_select_collection.map{|r| [i18n_status_helper(r),r]}, :include_blank => false %>
  <%= f.input :prepared_by, :input_html => {:value => f.object.prepared_by || current_admin_user.email, 
                                              :disabled => f.object.display_approved_by?} %>
  <% if f.object.display_approved_by? %>
    <%= f.input :approved_by, :input_html => {:value => f.object.approved_by || current_admin_user.email,
                                                :disabled => f.object.model_fixed?} %>
  <% end %>                         
<% end %>

<% if (f.object.change_histories.empty? || f.object.change_histories.last.persisted?)  %>
  <% f.object.change_histories.build(:updated_by => current_admin_user.email) %>
<% end %>
<%= f.inputs :notes, :updated_by, :name => :change_history, :for =>[:change_histories, f.object.change_histories.last] %>   